FROM rust:1.92 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release -p rps-agent

FROM debian:bookworm-slim
RUN mkdir -p /etc/rps
COPY --from=builder /app/target/release/rps-agent /usr/local/bin/rps-agent
COPY configs/docker-agent.toml /etc/rps/agent.toml
ENTRYPOINT ["/usr/local/bin/rps-agent"]
CMD ["--config", "/etc/rps/agent.toml"]
